-- Bootstrap inicial do Professor IA | AçõesJA
-- Execute uma vez no SQL Editor do Supabase ou com:
-- psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f supabase/bootstrap.sql
-- O script é idempotente e não contém credenciais.

begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_email_lowercase check (email = lower(email)),
  constraint profiles_full_name_length check (full_name is null or char_length(full_name) <= 120)
);

create unique index if not exists profiles_email_lower_key on public.profiles (lower(email));

create table if not exists public.launch_waitlist_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  full_name text,
  whatsapp text,
  marketing_consent boolean not null default false,
  attribution jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint launch_waitlist_email_lowercase check (email = lower(email)),
  constraint launch_waitlist_full_name_length check (full_name is null or char_length(full_name) <= 120),
  constraint launch_waitlist_whatsapp_length check (whatsapp is null or char_length(whatsapp) <= 30),
  constraint launch_waitlist_attribution_object check (jsonb_typeof(attribution) = 'object')
);

create unique index if not exists launch_waitlist_entries_email_key
  on public.launch_waitlist_entries (lower(email));

-- Catálogo pequeno e intencional do experimento da LP. Não representa a
-- cobertura total de ativos da plataforma principal.
create table if not exists public.professor_demo_assets (
  ticker text primary key,
  display_name text not null,
  display_order smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint professor_demo_assets_ticker_format check (ticker ~ '^[A-Z]{4}[0-9]{1,2}$'),
  constraint professor_demo_assets_display_name_present check (char_length(trim(display_name)) between 2 and 120)
);

create table if not exists public.professor_standard_questions (
  question_key text primary key,
  question_text text not null unique,
  display_order smallint not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint professor_standard_questions_key_format check (question_key ~ '^[a-z0-9_]+$'),
  constraint professor_standard_questions_text_present check (char_length(trim(question_text)) between 10 and 280)
);

create table if not exists public.professor_standard_answers (
  ticker text not null references public.professor_demo_assets(ticker) on delete cascade,
  question_key text not null references public.professor_standard_questions(question_key) on delete cascade,
  answer_markdown text not null,
  investigation_hint text not null,
  source_label text not null default 'Conteúdo educacional AçõesJA',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ticker, question_key),
  constraint professor_standard_answers_answer_present check (char_length(trim(answer_markdown)) between 40 and 6000),
  constraint professor_standard_answers_hint_present check (char_length(trim(investigation_hint)) between 10 and 1000)
);

-- Eventos de validação não guardam pergunta livre, resposta, e-mail ou
-- outro dado digitado. O session_id é aleatório e local ao navegador.
create table if not exists public.lp_interaction_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  ticker text references public.professor_demo_assets(ticker) on delete set null,
  question_key text references public.professor_standard_questions(question_key) on delete set null,
  properties jsonb not null default '{}'::jsonb,
  constraint lp_interaction_events_name_format check (event_name ~ '^[a-z][a-z0-9_]{2,63}$'),
  constraint lp_interaction_events_properties_object check (jsonb_typeof(properties) = 'object'),
  constraint lp_interaction_events_properties_size check (octet_length(properties::text) <= 2048)
);

create index if not exists lp_interaction_events_occurred_at_idx
  on public.lp_interaction_events (occurred_at desc);
create index if not exists lp_interaction_events_event_name_idx
  on public.lp_interaction_events (event_name, occurred_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
      updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute procedure public.set_updated_at();

drop trigger if exists launch_waitlist_set_updated_at on public.launch_waitlist_entries;
create trigger launch_waitlist_set_updated_at before update on public.launch_waitlist_entries
  for each row execute procedure public.set_updated_at();

drop trigger if exists professor_demo_assets_set_updated_at on public.professor_demo_assets;
create trigger professor_demo_assets_set_updated_at before update on public.professor_demo_assets
  for each row execute procedure public.set_updated_at();

drop trigger if exists professor_standard_questions_set_updated_at on public.professor_standard_questions;
create trigger professor_standard_questions_set_updated_at before update on public.professor_standard_questions
  for each row execute procedure public.set_updated_at();

drop trigger if exists professor_standard_answers_set_updated_at on public.professor_standard_answers;
create trigger professor_standard_answers_set_updated_at before update on public.professor_standard_answers
  for each row execute procedure public.set_updated_at();

insert into public.professor_demo_assets (ticker, display_name, display_order)
values
  ('PETR4', 'Petrobras PN', 1),
  ('ITUB4', 'Itaú Unibanco PN', 2)
on conflict (ticker) do update set
  display_name = excluded.display_name,
  display_order = excluded.display_order,
  active = true;

insert into public.professor_standard_questions (question_key, question_text, display_order)
values
  ('profit_but_stock_fell', 'A empresa teve lucro. Então por que a ação caiu?', 1),
  ('high_pe_expensive', 'P/L alto significa que uma ação está cara?', 2)
on conflict (question_key) do update set
  question_text = excluded.question_text,
  display_order = excluded.display_order,
  active = true;

insert into public.professor_standard_answers (
  ticker, question_key, answer_markdown, investigation_hint
) values
  (
    'PETR4',
    'profit_but_stock_fell',
    'Em **PETR4**, lucro e preço da ação podem andar em direções diferentes porque o mercado compara o resultado com o que já esperava e tenta antecipar os próximos trimestres. Mesmo com lucro, a cotação pode cair se o resultado vier abaixo das expectativas, se petróleo e câmbio piorarem, se aumentarem investimentos ou se houver incerteza sobre preços de combustíveis, governança e dividendos.\n\nA pergunta mais útil não é apenas “houve lucro?”, mas **de onde ele veio, se foi recorrente e o que mudou nas expectativas futuras**. Esta é uma explicação educacional, não uma recomendação.',
    'Compare o lucro com o consenso, a geração de caixa, a dívida, o plano de investimentos, o Brent, o câmbio e a política de dividendos; depois observe a reação da cotação ao redor da divulgação.'
  ),
  (
    'PETR4',
    'high_pe_expensive',
    'Um **P/L alto não prova sozinho que PETR4 está cara**. Em uma empresa cíclica, o lucro do denominador pode estar temporariamente deprimido, elevando o múltiplo sem que o preço tenha subido. O inverso também ocorre: um P/L baixo pode refletir lucro perto do pico do ciclo ou riscos que o mercado já descontou.\n\nPara PETR4, leia o P/L junto com o ciclo do petróleo, câmbio, custos, investimentos, dívida, governança e sustentabilidade dos dividendos. **Múltiplos ganham sentido quando comparados no tempo e com empresas semelhantes.**',
    'Compare o P/L atual com o histórico da própria Petrobras e pares do setor, normalizando lucros extraordinários; confira também fluxo de caixa livre, EV/EBITDA e cenários para o Brent.'
  ),
  (
    'ITUB4',
    'profit_but_stock_fell',
    'Em **ITUB4**, apresentar lucro não garante alta da ação. O mercado avalia se o resultado superou as expectativas e se a qualidade do lucro parece sustentável. A cotação pode cair diante de piora esperada na inadimplência, aumento do custo de crédito, pressão na margem financeira, despesas maiores ou uma projeção futura mais fraca, mesmo que o lucro atual seja positivo.\n\nTambém importa separar efeitos recorrentes de itens extraordinários. **O preço reage à diferença entre resultado, expectativa e perspectiva**, não somente ao sinal positivo do lucro.',
    'Compare lucro recorrente e consenso, ROE, margem financeira, inadimplência, cobertura, custo de crédito e guidance; observe também se a reação ocorreu antes da divulgação.'
  ),
  (
    'ITUB4',
    'high_pe_expensive',
    'Um **P/L alto não basta para concluir que ITUB4 está cara**. Ele pode refletir expectativa de lucros mais previsíveis, boa rentabilidade, crescimento ou menor risco percebido. Também pode subir porque o lucro do período caiu temporariamente, sem que a cotação tenha avançado.\n\nEm bancos, combine o P/L com **P/VP e ROE**: pagar mais sobre o patrimônio pode fazer sentido quando a instituição gera retorno superior e sustentável, mas essa hipótese precisa resistir a cenários de inadimplência, custo de crédito e pressão nas margens.',
    'Compare P/L, P/VP e ROE de ITUB4 com seu próprio histórico e bancos semelhantes; verifique crescimento do lucro recorrente, qualidade da carteira de crédito e custo de risco.'
  )
on conflict (ticker, question_key) do update set
  answer_markdown = excluded.answer_markdown,
  investigation_hint = excluded.investigation_hint,
  source_label = excluded.source_label,
  active = true;

-- Entrada pública mínima para a lista de lançamento. A tabela continua privada.
create or replace function public.join_launch_waitlist(
  p_email text,
  p_full_name text default null,
  p_whatsapp text default null,
  p_marketing_consent boolean default false,
  p_attribution jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(trim(p_email));
  v_id uuid;
begin
  if v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'E-mail inválido' using errcode = '22023';
  end if;

  if nullif(trim(p_full_name), '') is null then
    raise exception 'Nome é obrigatório' using errcode = '22023';
  end if;

  if coalesce(p_marketing_consent, false) is not true then
    raise exception 'O consentimento para receber avisos e novidades é obrigatório' using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_attribution, '{}'::jsonb)) <> 'object' then
    raise exception 'Atribuição inválida' using errcode = '22023';
  end if;

  insert into public.launch_waitlist_entries (
    user_id, email, full_name, whatsapp, marketing_consent, attribution
  ) values (
    auth.uid(), v_email, nullif(trim(p_full_name), ''), nullif(trim(p_whatsapp), ''),
    p_marketing_consent, coalesce(p_attribution, '{}'::jsonb)
  )
  on conflict (lower(email)) do update set
    user_id = coalesce(excluded.user_id, public.launch_waitlist_entries.user_id),
    full_name = coalesce(excluded.full_name, public.launch_waitlist_entries.full_name),
    whatsapp = coalesce(excluded.whatsapp, public.launch_waitlist_entries.whatsapp),
    marketing_consent = public.launch_waitlist_entries.marketing_consent or excluded.marketing_consent,
    attribution = public.launch_waitlist_entries.attribution || excluded.attribution,
    updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.get_professor_standard_answer(
  p_ticker text,
  p_question_key text
)
returns table (
  ticker text,
  asset_name text,
  question_key text,
  question_text text,
  answer_markdown text,
  investigation_hint text,
  source_label text
)
language sql
stable
security definer
set search_path = ''
as $$
  select a.ticker, a.display_name, q.question_key, q.question_text,
         r.answer_markdown, r.investigation_hint, r.source_label
  from public.professor_standard_answers r
  join public.professor_demo_assets a on a.ticker = r.ticker
  join public.professor_standard_questions q on q.question_key = r.question_key
  where r.ticker = upper(trim(p_ticker))
    and r.question_key = trim(p_question_key)
    and r.active and a.active and q.active
  limit 1;
$$;

create or replace function public.record_lp_interaction(
  p_session_id uuid,
  p_event_name text,
  p_ticker text default null,
  p_question_key text default null,
  p_properties jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_ticker text := nullif(upper(trim(p_ticker)), '');
  v_question_key text := nullif(trim(p_question_key), '');
  v_properties jsonb := coalesce(p_properties, '{}'::jsonb);
begin
  if p_session_id is null then
    raise exception 'Sessão anônima inválida' using errcode = '22023';
  end if;
  if p_event_name !~ '^[a-z][a-z0-9_]{2,63}$' then
    raise exception 'Evento inválido' using errcode = '22023';
  end if;
  if jsonb_typeof(v_properties) <> 'object' or octet_length(v_properties::text) > 2048 then
    raise exception 'Propriedades inválidas' using errcode = '22023';
  end if;

  insert into public.lp_interaction_events (
    session_id, user_id, event_name, ticker, question_key, properties
  ) values (
    p_session_id, auth.uid(), p_event_name, v_ticker, v_question_key, v_properties
  ) returning id into v_id;

  return v_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.launch_waitlist_entries enable row level security;
alter table public.professor_demo_assets enable row level security;
alter table public.professor_standard_questions enable row level security;
alter table public.professor_standard_answers enable row level security;
alter table public.lp_interaction_events enable row level security;

drop policy if exists "profiles can view own data" on public.profiles;
create policy "profiles can view own data" on public.profiles
  for select to authenticated using ((select auth.uid()) = id);

drop policy if exists "profiles can update own data" on public.profiles;
revoke insert, update, delete on table public.profiles from anon, authenticated;
revoke all on table public.launch_waitlist_entries from anon, authenticated;
revoke all on table public.professor_demo_assets from anon, authenticated;
revoke all on table public.professor_standard_questions from anon, authenticated;
revoke all on table public.professor_standard_answers from anon, authenticated;
revoke all on table public.lp_interaction_events from anon, authenticated;
grant execute on function public.join_launch_waitlist(text, text, text, boolean, jsonb) to anon, authenticated;
grant execute on function public.get_professor_standard_answer(text, text) to anon, authenticated;
grant execute on function public.record_lp_interaction(uuid, text, text, text, jsonb) to anon, authenticated;

commit;
